[[main]]
none = "none"

[[main]]
name = "events"
pre = "location-dot"
pageRef = "events/"
identifier = "56fSZffm22"
weight = 1

[[main]]
name = "About"
pre = "globe"
pageRef = "/about"
identifier = "oLoJiRRx1S"
weight = 3

[[main]]
name = "Sponsor"
pre = "patreon"
pageRef = "sponsor"
identifier = "5qEagbDFGL"
weight = 2

[[footer]]
none = "none"

[[footer]]
name = "GitHub"
pre = "github"
url = "https://github.com/socallinuxexpo/cloud-native-days-web"
weight = 10
